---
title: "Practice June 2"
output: html_notebook
---


```{r}
# Number
x <- 2
# Text
name <- "Thomas"
```

```{r}
# Boolean
flag <- TRUE
```

```{r}
color <- factor(c("Red", "Blue", "Green"))
```

```{r}
names <- c("Alice", "Bob", "Bob2")
names
```

```{r}
my_list <- list(name = "Alice", age=25, scores = c(95, 85, 88))
my_list
```
```{r}
students <- data.frame(
  name = c("Alice", "Bob"), 
  age = c(23,24),
  score = c(89, 92)
)
students
```

```{r}
nums <- c(1,2,3,4)
sum(nums)
```

```{r}
mean(nums)
length(nums)
```

```{r}
install.packages("ggplot2")
library(ggplot2)
```
```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)
library(maps)
```

```{r}
# Get map data for US states
state_map <- map_data("state")
```

```{r}
head(state_map)
```

```{r}
regions.df <- data.frame(
  region = c("california", "texas", "new york", "florida", "illinois", "washington"),
  rep.region = c("West", "South", "Northeast", "South", "Midwest", "West")
)
```

```{r}
# join state map with regions
df <- left_join(state_map, regions.df, by = "region")
```

```{r}
# Create the map
ggplot(df) +
  aes(long, lat, group=group) +
  geom_polygon(aes(fill = rep.region), color = "white") +
  labs(x = "", y = "",
       title = "Wine Sales Regions",
       subtitle = "Which States in Each Region") +
  theme (
    axis.text = element_blank(), 
    axis.ticks = element_blank(),
    panel.background = element_blank()
  ) +
  coord_map("albers", at0 = 45.5, lat1 = 29.5)
```










